### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by al2b** [WildCodeSchool/Lyon-0917-MarketingAutomation#358]
Faire une image avec un carré bleu de la couleur du site, adapter la taille au format favicon, mettre en ligne

@fannyperret : ça t'intéresse de prendre cette tâche ?

**Comment by fannyperret** [comment]
Ouiiii

El 16/1/2018 11:05, "al2b" <notifications@github.com> escribió:

Faire une image avec un carré bleu de la couleur du site, adapter la taille
au format favicon, mettre en ligne

@fannyperret <https://github.com/fannyperret> : ça t'intéresse de prendre
cette tâche ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/WildCodeSchool/Lyon-0917-MarketingAutomation/issues/358>,
or mute the thread

**Comment by al2b** [comment]
je ferme cette issue puisque Pierre en a créé une nouvelle
